# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_Date', models.CharField(max_length=50)),
                ('Service_Days', models.CharField(max_length=50)),
                ('Order_Code', models.CharField(max_length=135)),
                ('Contact_App', models.CharField(max_length=135)),
                ('First_Name', models.CharField(max_length=135)),
                ('Surname', models.CharField(max_length=135)),
                ('Email', models.CharField(max_length=135)),
                ('Payment_Status', models.CharField(max_length=135)),
                ('Order_Date', models.CharField(max_length=135)),
                ('Social_Profile', models.CharField(max_length=135)),
                ('Social_Profile_Name', models.CharField(max_length=135)),
                ('Promo_Code', models.CharField(max_length=135)),
                ('Net_Price', models.CharField(max_length=135)),
                ('Discount', models.CharField(max_length=135)),
                ('Payment_Fee', models.CharField(max_length=135)),
                ('Total', models.CharField(max_length=135)),
            ],
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='comment',
        ),
        migrations.AddField(
            model_name='myappuser',
            name='status',
            field=models.TextField(blank=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='myappuser',
            name='code',
            field=models.CharField(max_length=135, verbose_name='Promo Code'),
        ),
    ]
