# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20161212_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='status',
            field=models.TextField(blank=True, verbose_name='Status    '),
        ),
    ]
