# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20161214_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
