# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_auto_20161214_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myappuser',
            name='code',
        ),
        migrations.AddField(
            model_name='clients',
            name='connection_came_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water.MyAppUser'),
        ),
        migrations.AddField(
            model_name='clients',
            name='promo_kind_code',
            field=models.CharField(blank=True, max_length=135),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='code_metapolishs',
            field=models.CharField(blank=True, max_length=135),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='code_paroxhs',
            field=models.CharField(blank=True, max_length=135),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='pososto_xrewshs_metapolishs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='pososto_xrewshs_paroxhs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
