# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_auto_20161215_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_travelers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kathgoria', models.IntegerField(blank=True, null=True)),
                ('Cost_per_traveler', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='pososto_xrewshs_metapolishs',
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='pososto_xrewshs_paroxhs',
        ),
        migrations.AddField(
            model_name='myappuser',
            name='price_per_traveler_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prwth', to='water.Number_of_travelers'),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='price_per_traveler_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Deuterh', to='water.Number_of_travelers'),
        ),
        migrations.AddField(
            model_name='myappuser',
            name='price_per_traveler_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trith', to='water.Number_of_travelers'),
        ),
    ]
