# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_auto_20161221_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappuser',
            name='price_paroxhs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
