# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_auto_20161221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Order_Date',
            field=models.DateField(verbose_name='Order Date'),
        ),
    ]
