# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_auto_20161222_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number_of_travelers',
            old_name='Cost_per_traveler',
            new_name='Cost_per_traveler_deuterhs_kathgorias',
        ),
        migrations.RenameField(
            model_name='number_of_travelers',
            old_name='kathgoria',
            new_name='maximum_travelers_deuterhs_kathgorias',
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='price_per_traveler_1',
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='price_per_traveler_2',
        ),
        migrations.RemoveField(
            model_name='myappuser',
            name='price_per_traveler_3',
        ),
        migrations.AddField(
            model_name='myappuser',
            name='price_per_traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pinakas', to='water.Number_of_travelers'),
        ),
        migrations.AddField(
            model_name='number_of_travelers',
            name='Cost_per_traveler_prwths_kathgorias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='number_of_travelers',
            name='Cost_per_traveler_triths_kathgorias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='number_of_travelers',
            name='maximum_travelers_prwths_kathgorias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
