# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_auto_20161228_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number_of_travelers',
            options={'verbose_name': 'Pinakas Timwn'},
        ),
    ]
