# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_auto_20161228_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Arrival_Date',
            field=models.CharField(max_length=50, verbose_name='Arrival Date'),
        ),
    ]
