# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0015_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='fordate',
            field=models.DateField(null=True),
        ),
    ]
