# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0016_auto_20170112_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers_served',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fordate', models.DateField(null=True)),
                ('no_of_sales', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(default=0)),
                ('settled', models.CharField(choices=[('p', 'Pending'), ('c', 'Complete')], default='p', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.MyAppUser')),
            ],
        ),
    ]
